# Generated by Django 4.2.7 on 2023-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["published_date"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="distribution_expense",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
